---
- name: set hostname
  hostname: name=dev
  sudo: yes

- name: install vim
  apt: pkg=vim state=present
  sudo: yes

- name: install git
  apt: pkg=git state=present
  sudo: yes

- name: copy vimrc
  copy: src=~/.vimrc dest=~vagrant/.vimrc

- name: copy bashrc
  copy: src=../bashrc dest=~vagrant/.bashrc

- name: set name in git
  command: git config --global user.name "{{ git_username }}"

- name: set email in git
  command: git config --global user.email "{{ git_email }}"

- name: copy pub key
  copy: src=~/.ssh/id_dsa.pub dest=~vagrant/.ssh/id_dsa.pub

- name: copy priv key
  copy: src=~/.ssh/id_dsa dest=~vagrant/.ssh/id_dsa
