# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    config.vm.box = "wheezy64_fusion"
    config.vm.box_url = "https://dl.dropboxusercontent.com/u/1752352/wheezy64_fusion.box"

    config.vm.provider :vmware_fusion do |v|
        v.vmx["memsize"] = "4096"
        v.vmx["numvcpus"] = "2"

        # Enable Intel VT-x/EPT virtualization in VM so we can boot guests
        v.vmx["vhv.enable"] = "TRUE"
    end

    # General dev box related setups
    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "../dev.yaml"
        #ansible.verbose = "v"
        ansible.host_key_checking = false
    end

    # Setup useful python related bits
    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "../python.yaml"
        ansible.host_key_checking = false
        #ansible.verbose = "v"
    end

    # Setup Nova releated dependencies
    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "../nova.yaml"
        ansible.host_key_checking = false
        #ansible.verbose = "v"
    end
end
