# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "wheezy64_fusion"
  config.vm.box_url = "https://dl.dropboxusercontent.com/u/1752352/wheezy64_fusion.box"
end
